defaults: &defaults
 
:development:
  :sqlite3:
    :adapter: sqlite3
    :database: db/development.sqlite3
    <<: *defaults

:test:
  :sqlite3:
    :database: db/test.sqlite3
    <<: *defaults

:production:
  :postgresql:
    :database: wykwikptpr
    :port: 5432
    :host: ec2-50-17-202-49.compute-1.amazonaws.com
    :username: wykwikptpr
    :password: mjFU9U3czhtvB2FufjCN
    <<: *defaults
